version: "3"

services:
  database:
    container_name: database
    image: "postgres:12.12-alpine"
    restart: "unless-stopped"
    env_file: .backend.env
    networks:
      - db-network
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: "unless-stopped"
    env_file: .backend.env
    networks:
      - db-network
      - network
    ports:
      - "4000:3000"
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: "unless-stopped"
    networks:
      - network
    ports:
      - "8081:80"

networks:
  db-network:
    driver: bridge
    internal: true
  network:
    driver: bridge

volumes:
  db-volume:
    driver: local
